import 'package:spree/Utils/config.dart';

class languages {
  //Duplicate this object and translate it to there respective language
  static var english_objects = {
    "app_name": "Orderista POS",
    "app_title": "",
    "app_tagline": "",
    "app_info": "",
    "store": "A simplified point of sale",
    "wt1": "Works Offline",
    "wc1": "Orderista POS works offline when network is lost",
    "wt2": "Sync Data Automatically",
    "wc2": "Orderista POS automatically syncs data in between devices and backend",
    "wt3": "Offline and Online Payments",
    "wc3": "Orderista POS supports different channels of payments",
    "wt4": "Manage Stock Easily",
    "wc4": "Orderista POS allows you to take control of your inventory",
    "skip": "SKIP",
    "next": "NEXT",
    "gotIt": "GOT IT",
    "title_store_brands": "Store Brands",
    "title_store_category": "Product Category",
    "title_make_purchase": "Make Product Purchase",
    "enter_ref_number": "Enter Purchase Ref No.",
    "ref_no": "Ref No",
    "enter_receiving_quantity": "Enter Receiving Quantity",
    "units": "Skus",
    "enter_single_product_cost": "Enter Single Product Cost",
    "product_cost": "Product Cost",
    "create_product": "CREATE PURCHASE",
    "enter_all_fields": "Enter All Fields",
    "purchase_successful": "Purchase successful",
    "choose": "Choose",
    "choose_payment_status": "Choose Payment Status",
    "choose_purchase_status": "Choose Purchase Status",
    "choose_supplier": "Choose Supplier",
    "title_store_customer": "Store Customers",
    "customer_activity": "Customer Activity Logs",
    "msg_stall_does_not_exist": "Stall does not exist",
    "device_exists_more_than_one_instance":
        "Device exists more than one instance",
    "device_not_connected_to_any_stall": "Device Not Connected to any Stall",
    "no_brands_found": "No brands found",
    "no_categories_found": "No categories found",
    "no_units_found": "No Units found",
    "no_customers_found": "No Customers found",
    "no_suppliers_found": "No Suppliers found",
    "no_tax_found": "No Tax found",
    "no_products_found": "No products found",
    "user_not_created_on_db": "User not created on DB",
    "no_stalls_found": "No Stalls found",
    "dashboard": "Dashboard",
    "pos": "POS",
    "reports": "Reports",
    "settings": "Settings",
    "store_outlets": "Store Outlets",
    "store_outlets_type": "Store Outlets Type",
    "store_expenses": "Store Expenses",
    "forgot_password": "Forgot Password",
    "you_will_receive_an_email_confirming_your_new_password":
        "You will receive an email confirming your new password",
    "enter_your_email_adress": "Enter your Email Address",
    "email": "Email",
    "send": "SEND",
    "back_to_login": "Back To Login",
    "password_link_sent": "Password Link Sent",
    "stock_management": "Stock Management",
    "inventory": "Inventory",
    "check_your_store_inventory": "Check your Store Inventory",
    "store_sales": "Store Sales",
    "check_your_stall_sales": "Check your Stall Sales",
    "product_brand": "Product Brands",
    "check_your_product_brands": "Check your Product Brands",
    "product_categories": "Product Categories",
    "check_your_product_categories": "Check your Product Categories",
    "price": "Price",
    "inventory": "Inventory",
    "sold": "Sold",
    "bought": "Bought",
    "product_details": "Product Details",
    "product_brand": "Product Brand",
    "product_label_type": "Product Label Type",
    "product_unit": "Product Unit",
    "stall_inventory": "Stall Inventory",
    "sku": "SKU",
    "store_outlets": "Store Outlets",
    "welcome_back": "Welcome Back",
    "sign_in_to_continue": "Sign in to continue",
    "enter_your_email_address": "Enter your Email Address",
    "enter_your_password": "Enter your password",
    "password": "Password",
    "sign_in": "SIGN IN",
    "enter_all_your_fields": "Enter all Fields",
    "forgot_password": "Forgot Password",
    "signup": "Signup",
    "terms_and_condition": "Terms and Condition",
    "could_not_launch": "Could not launch",
    "store_notice": "Store Notice",
    "make_sale": "Make Sale",
    "total_product_on_cart": "Total Products on Cart",
    "total_items_on_cart": "Total Items on Cart",
    "total_amount_on_cart": "Total Amount on Cart",
    "total_tax_amount_on_cart": "Total tax amount on Cart",
    "product_inventory_empty": "Product Inventoty Empty",
    "msg_item_removed": "Item removed",
    "choose_customer": "Choose Customer",
    "enter_discount": "Enter Discount",
    "enter_sale_discount": "Enter Sale Discount.",
    "sale_discount": "Sale Discount",
    "cash": "Cash",
    "pay_by_cash": "Pay by cash",
    "online_payments_comming_soon": "Online Payments Comming Soon",
    "online": "Online",
    "credit": "Credit",
    "pay_by_credit": "Pay by Credit",
    "customer_order_limit_is_below": "Customer order limit is below",
    "bank": "Bank",
    "pay_by_bank": "Pay by Bank",
    "product_not_set_kindly_restock_product":
        "Product Not Set, Kindly restock product",
    "units": "Units",
    "setting_language": "Setting Language",
    "complete_cash_checkout": "COMPLETE CASH CHECKOUT",
    "": "COMPLETE CASH CHECKOUT",
    "you_are_about_to_check_out_with_cash_payment":
        "You are about to check out with cash payment",
    "enter_bank_note": "Enter Bank Note",
    "bank_note": "Bank Note",
    "cancel": "CANCEL",
    "complete": "COMPLETE",
    "you_need_to_enter_bank_note": "You need to enter bank note",
    "complete_cash_checkout": "COMPLETE CASH CHECKOUT",
    "you_are_about_to_check_out_with_cash_payment":
        "You are about to check out with cash payment",
    "complete_credit_checkout": "COMPLETE CREDIT CHECKOUT",
    "you_are_about_to_check_out_with_credit_payment":
        "You are about to check out with credit payment",
    "kindly_choose_a_customer": "Kindly choose a customer",
    "scan_or_enter_keyword": "Scan or Enter keyword",
    "enter_keyword_or_barcode": "Enter keyword or barcode",
    "you_need_to_enter_keyword": "You need to enter keyword",
    "for_enquiries_call": "FOR ENQUIRIES CALL",
    "receipt": "RECEIPT",
    "total_amount": "TOTAL AMOUNT",
    "total_items": "TOTAL ITEMS",
    "total_tax": "TOTAL TAX",
    "thant_you_and_come_again": "THANK YOU & COME AGAIN",
    "product_unit": "Product Unit",
    "units_state": "Units State",
    "product_sale_history": "Product Sale History",
    "total_sales": "Total sales",
    "sales": "Sales",
    "total_customers": "Total Customers",
    "customers": "Customers",
    "total_suppliers": "Total Suppliers",
    "suppliers": "Suppliers",
    "total_inventory": "Total Inventory",
    "items": "Items",
    "total_devices": "Total Devices",
    "devices": "Devices",
    "total_purchases": "Total Purchases",
    "purchases": "Purchases",
    "total_stalls": "Total Stalls",
    "stalls": "Stalls",
    "store_returns": "Store Returns",
    "stall_sales": "Stall Sales",
    "receipt_amount": "Receipt Amount",
    "not_loaded": "Not Loaded",
    "store_detail": "Store Detail",
    "check_your_store_detail": "Check your Store Detail",
    "merchant_outlets": "Merchant Outlets",
    "check_all_your_retail_outlets": "Check all your Retail Outlets",
    "store_Staff": "Store Staff",
    "check_all_your_store_staff": "Check all your store Staff",
    "store_Check_all_your_store_sustomer": "Check all your store Customer",
    "store_supplier": "Store Supplier",
    "check_all_your_store_supplier": "Check all your store Supplier",
    "product_units": "Product Units",
    "view_your_products_units": "View your products units",
    "tax": "Tax",
    "view_tax_class": "View Tax Class",
    "Orderista POS_welcomes_you": "Orderista POS Welcomes you",
    "signin_to_manage_youre_store": "Signin to manage your store",
    "enter_your_email_address": "Enter your Email Address",
    "creating_your_account": "Creating your account...",
    "enter_all_Fields": "Enter all Fields",
    "back_to_login": "Back To Login",
    "terms_and_condition": "Terms and Condition",
    "welcome_to": "Welcome to ",
    "loading_product_details": "Loading Product Details",
    "staff_activity_logs": "Staff Activity Logs",
    "stall_staffs": "Stall Staffs",
    "store_online_status": "Store Online Status",
    "store_visibility": "Store Visibility",
    "stall_is": "Stall is",
    "store_stock_transfer": "Store Stock Transfer",
    "store_tax_classes": "Store Tax Classes",
    "details": "Details",
    "loading_suppliers": "Loading Suppliers...",
    "store_suppliers": "Store Suppliers",
    "supplier_name_is": "Supplier Name is",
    "supplier_purchases": "Supplier Purchases",
    "pay_customer_credit": "Pay Customer Credit",
    "pay_customer_credit_confirm": "You are about to pay this customer credit of ",
    "enter_amount_to_be_paid" : "Enter amount to be paid",
    "amount_to_be_paid" : "Amount to be paid",
    "credit_payment_can_not_exeed_balance": "You cant pay more than ",
    "amount" : "Amount",
    "credit_paid": "Credit Paid",
  };

  static var swahili_objects = {
    "app_name": "Orderista POS",
    "app_title": "",
    "app_tagline": "",
    "app_info": "",
    "store": "A simplified point of sale",
    "wt1": "Works Offline",
    "wc1": "Orderista POS works offline when network is lost",
    "wt2": "Sync Data Automatically",
    "wc2": "Orderista POS automatically syncs data in between devices and backend",
    "wt3": "Offline and Online Payments",
    "wc3": "Orderista POS supports different channels of payments",
    "wt4": "Manage Stock Easily",
    "wc4": "Orderista POS allows you to take control of your inventory",
    "skip": "SKIP",
    "next": "NEXT",
    "gotIt": "GOT IT",
    "title_store_brands": "Store Brandi",
    "title_store_category": "Product Category",
    "title_make_purchase": "Make Product Purchase",
    "enter_ref_number": "Enter Purchase Ref No.",
    "ref_no": "Ref No",
    "enter_receiving_quantity": "Enter Receiving Quantity",
    "units": "Units",
    "enter_single_product_cost": "Enter Single Product Cost",
    "product_cost": "Product Cost",
    "create_product": "CREATE PURCHASE",
    "enter_all_fields": "Enter All Fields",
    "purchase_successful": "Purchase successful",
    "choose": "Choose",
    "choose_payment_status": "Choose Payment Status",
    "choose_purchase_status": "Choose Purchase Status",
    "choose_supplier": "Choose Supplier",
    "title_store_customer": "Store Customers",
    "customer_activity": "Customer Activity Logs",
    "msg_stall_does_not_exist": "Stall does not exist",
    "device_exists_more_than_one_instance":
        "Device exists more than one instance",
    "device_not_connected_to_any_stall": "Device Not Connected to any Stall",
    "no_brands_found": "No brands found",
    "no_categories_found": "No categories found",
    "no_units_found": "No Units found",
    "no_customers_found": "No Customers found",
    "no_suppliers_found": "No Suppliers found",
    "no_tax_found": "No Tax found",
    "no_products_found": "No products found",
    "user_not_created_on_db": "User not created on DB",
    "no_stalls_found": "No Stalls found",
    "dashboard": "Dashboard",
    "pos": "POS",
    "reports": "Reports",
    "settings": "Settings",
    "store_outlets": "Store Outlets",
    "store_outlets_type": "Store Outlets Type",
    "store_expenses": "Store Expenses",
    "forgot_password": "Forgot Password",
    "you_will_receive_an_email_confirming_your_new_password":
        "You will receive an email confirming your new password",
    "enter_your_email_adress": "Enter your Email Address",
    "email": "Email",
    "send": "SEND",
    "back_to_login": "Back To Login",
    "password_link_sent": "Password Link Sent",
    "stock_management": "Stock Management",
    "inventory": "Inventory",
    "check_your_store_inventory": "Check your Store Inventory",
    "store_sales": "Store Sales",
    "check_your_stall_sales": "Check your Stall Sales",
    "product_brand": "Product Brands",
    "check_your_product_brands": "Check your Product Brands",
    "product_categories": "Product Categories",
    "check_your_product_categories": "Check your Product Categories",
    "price": "Price",
    "inventory": "Inventory",
    "sold": "Sold",
    "bought": "Bought",
    "product_details": "Product Details",
    "product_brand": "Product Brand",
    "product_label_type": "Product Label Type",
    "product_unit": "Product Unit",
    "stall_inventory": "Stall Inventory",
    "sku": "SKU",
    "store_outlets": "Store Outlets",
    "welcome_back": "Welcome Back",
    "sign_in_to_continue": "Sign in to continue",
    "enter_your_email_address": "Enter your Email Address",
    "enter_your_password": "Enter your password",
    "password": "Password",
    "sign_in": "SIGN IN",
    "enter_all_your_fields": "Enter all Fields",
    "forgot_password": "Forgot Password",
    "signup": "Signup",
    "terms_and_condition": "Terms and Condition",
    "could_not_launch": "Could not launch",
    "store_notice": "Store Notice",
    "make_sale": "Make Sale",
    "total_product_on_cart": "Total Products on Cart",
    "total_items_on_cart": "Total Items on Cart",
    "total_amount_on_cart": "Total Amount on Cart",
    "total_tax_amount_on_cart": "Total tax amount on Cart",
    "product_inventory_empty": "Product Inventoty Empty",
    "msg_item_removed": "Item removed",
    "choose_customer": "Choose Customer",
    "enter_discount": "Enter Discount",
    "enter_sale_discount": "Enter Sale Discount.",
    "sale_discount": "Sale Discount",
    "cash": "Cash",
    "pay_by_cash": "Pay by cash",
    "online_payments_comming_soon": "Online Payments Comming Soon",
    "online": "Online",
    "credit": "Credit",
    "pay_by_credit": "Pay by Credit",
    "customer_order_limit_is_below": "Customer order limit is below",
    "bank": "Bank",
    "pay_by_bank": "Pay by Bank",
    "product_not_set_kindly_restock_product":
        "Product Not Set, Kindly restock product",
    "units": "Units",
    "setting_language": "Setting Language",
    "complete_cash_checkout": "COMPLETE CASH CHECKOUT",
    "": "COMPLETE CASH CHECKOUT",
    "you_are_about_to_check_out_with_cash_payment":
        "You are about to check out with cash payment",
    "enter_bank_note": "Enter Bank Note",
    "bank_note": "Bank Note",
    "cancel": "CANCEL",
    "complete": "COMPLETE",
    "you_need_to_enter_bank_note": "You need to enter bank note",
    "complete_cash_checkout": "COMPLETE CASH CHECKOUT",
    "you_are_about_to_check_out_with_cash_payment":
        "You are about to check out with cash payment",
    "complete_credit_checkout": "COMPLETE CREDIT CHECKOUT",
    "you_are_about_to_check_out_with_credit_payment":
        "You are about to check out with credit payment",
    "kindly_choose_a_customer": "Kindly choose a customer",
    "scan_or_enter_keyword": "Scan or Enter keyword",
    "enter_keyword_or_barcode": "Enter keyword or barcode",
    "you_need_to_enter_keyword": "You need to enter keyword",
    "for_enquiries_call": "FOR ENQUIRIES CALL",
    "receipt": "RECEIPT",
    "total_amount": "TOTAL AMOUNT",
    "total_items": "TOTAL ITEMS",
    "total_tax": "TOTAL TAX",
    "thant_you_and_come_again": "THANK YOU & COME AGAIN",
    "product_unit": "Product Unit",
    "units_state": "Units State",
    "product_sale_history": "Product Sale History",
    "total_sales": "Total sales",
    "sales": "Sales",
    "total_customers": "Total Customers",
    "customers": "Customers",
    "total_suppliers": "Total Suppliers",
    "suppliers": "Suppliers",
    "total_inventory": "Total Inventory",
    "items": "Items",
    "total_devices": "Total Devices",
    "devices": "Devices",
    "total_purchases": "Total Purchases",
    "purchases": "Purchases",
    "total_stalls": "Total Stalls",
    "stalls": "Stalls",
    "store_returns": "Store Returns",
    "stall_sales": "Stall Sales",
    "receipt_amount": "Receipt Amount",
    "not_loaded": "Not Loaded",
    "store_detail": "Store Detail",
    "check_your_store_detail": "Check your Store Detail",
    "merchant_outlets": "Merchant Outlets",
    "check_all_your_retail_outlets": "Check all your Retail Outlets",
    "store_Staff": "Store Staff",
    "check_all_your_store_staff": "Check all your store Staff",
    "store_Check_all_your_store_sustomer": "Check all your store Customer",
    "store_supplier": "Store Supplier",
    "check_all_your_store_supplier": "Check all your store Supplier",
    "product_units": "Product Units",
    "view_your_products_units": "View your products units",
    "tax": "Tax",
    "view_tax_class": "View Tax Class",
    "Orderista POS_welcomes_you": "Orderista POS Welcomes you",
    "signin_to_manage_youre_store": "Signin to manage your store",
    "enter_your_email_address": "Enter your Email Address",
    "creating_your_account": "Creating your account...",
    "enter_all_Fields": "Enter all Fields",
    "back_to_login": "Back To Login",
    "terms_and_condition": "Terms and Condition",
    "welcome_to": "Welcome to ",
    "loading_product_details": "Loading Product Details",
    "staff_activity_logs": "Staff Activity Logs",
    "stall_staffs": "Stall Staffs",
    "store_online_status": "Store Online Status",
    "store_visibility": "Store Visibility",
    "stall_is": "Stall is",
    "store_stock_transfer": "Store Stock Transfer",
    "store_tax_classes": "Store Tax Classes",
    "details": "Details",
    "loading_suppliers": "Loading Suppliers...",
    "store_suppliers": "Store Suppliers",
    "supplier_name_is": "Supplier Name is",
    "supplier_purchases": "Supplier Purchases",
  };

  //link language to their object translations
  static var skeleton_language_objects = {
    "english": english_objects,
    "swahili": swahili_objects,
  };
}
